# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
# Scrape Prometheus itself every 5 seconds.
- job_name: 'prometheus'
  scrape_interval: 5s
  target_groups:
  - targets: ['localhost:9090']

- job_name: 'container-exporter'
  scrape_interval: 5s
  target_groups:
      - targets: ['container-exporter:9104']

#- job_name: 'consul'
#  consul_sd_config:
#  - server: 'consul'
#    services:
- job_name: service-y
  consul_sd_configs:
      - server: '127.0.0.1:8500'
        services: ['app1']


# Scrape the Node Exporter every 5 seconds.
#  - job_name: 'node'
#    scrape_interval: 5s
#    target_groups:
#      - targets: ['your_server_ip:9100']

#job: {
#  name: "container-exporter"
#  scrape_interval: "1m"
#  target_group: {
#      labels: {
#        label: {
#            name: "zone"
#            value: "us-east-1"
#        }
#        label: {
#            name: "env"
#            value: "prod"
#        }
#    }
#    target: "http://1.2.3.4:8080/metrics"
#  }
#}

