# A scrape configuration scraping a Node Exporter and the Prometheus server
# itself.

global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
# Scrape Prometheus itself every 5 seconds.
- job_name: 'prometheus'
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']

- job_name: 'container-exporter'
  static_configs:
      - targets: ['container-exporter:9104']

- job_name: 'consul'
  consul_sd_configs:
      - server: 'consul:8500'

- job_name: 'consul-exporter'
  static_configs:
  - targets: ['consul-exporter:9107']

- job_name: 'localrealhost'
  static_configs:
  - targets: ['node-exporter:9100']


rule_files:
    - 'alert.rules'

